import { Metadata } from 'next'
import ProjectCard from '@/components/project-card'
import { experiences, projects } from '@/utils/projects'

export const metadata: Metadata = {
  title: 'Some of my work',
  description: 'Generated by create next app',
}

const formatTime = (time: string) => (time.startsWith("'") ? time : time.replace(/^(\d{2})/, "'$1"))

const page = () => {
  return (
    <div className="space-y-12 text-[#D6D6DC]">
      <section className="space-y-6">
        <h2 className="text-xs text-yellow-400">work</h2>
        <div className="space-y-8">
          {experiences.map((experience) => (
            <article key={experience.workplace} className="space-y-2">
              <div className="text-base font-semibold text-white">{experience.workplace}</div>
              <div className="text-[#9CA3AF]">
                <div className="text-xs lowercase">{experience.position}</div>
                <div className="text-xs lowercase text-[#6B7280]">{formatTime(experience.time)}</div>
              </div>
              <p className="text-xs lowercase text-[#D1D5DB]">{experience.description}</p>
            </article>
          ))}
        </div>
      </section>

      <h2 className="text-xs text-yellow-400">projects</h2>
      <section className="grid gap-x-6 gap-y-1 md:grid-cols-2">
        {projects.map((project) => (
          <ProjectCard
            key={project.title}
            title={project.title}
            description={project.description}
            imgUrl={project.imgUrl}
            seeCode={project.seeCode}
            liveSite={project.liveSite}
            tech={project.tech}
            status={project.status}
          />
        ))}
      </section>
    </div>
  )
}
export default page
