import { Metadata } from 'next'
import projects from '@/utils/projects'
import ProjectCard from '@/components/project-card'

export const metadata: Metadata = {
  title: 'Some of my work',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div className="grid gap-x-6 gap-y-1 text-[#D4D4D4] md:grid-cols-2">
      {projects.map((project) => (
        <ProjectCard
          key={project.title}
          title={project.title}
          description={project.description}
          imgUrl={project.imgUrl}
          seeCode={project.seeCode}
          liveSite={project.liveSite}
          tech={project.tech}
          status={project.status}
        />
      ))}
    </div>
  )
}

export default page
