import { Metadata } from 'next'
import Link from 'next/link'
import ProjectCard from '@/components/project-card'
import { experiences, projects } from '@/utils/projects'

export const metadata: Metadata = {
  title: 'Some of my work',
  description: 'Generated by create next app',
}

const formatTime = (time: string) => (time.startsWith("'") ? time : time.replace(/^(\d{2})/, "'$1"))

const page = () => {
  return (
    <div className="space-y-12 text-[#D6D6DC]">
      <section className="space-y-6">
        <h2 className="text-xs text-yellow-400">work</h2>
        <div className="space-y-8">
          {experiences.map((experience) => (
            <article key={experience.workplace} className="space-y-2">
              <Link
                href={experience.href}
                className="group inline-flex items-center text-base font-semibold text-white transition-colors duration-150 hover:text-[#FACC15]"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span className="relative inline-flex items-center">
                  <span
                    aria-hidden
                    className="absolute -left-4 inline-block text-xs text-[#FACC15] opacity-0 transition-all duration-150 group-hover:-left-6 group-hover:opacity-100"
                  >
                    →
                  </span>
                  <span>{experience.workplace}</span>
                </span>
              </Link>
              <div className="text-[#9CA3AF]">
                <div className="text-xs lowercase">{experience.position}</div>
                <div className="text-xs lowercase text-[#6B7280]">{formatTime(experience.time)}</div>
              </div>
              <p className="text-xs lowercase text-[#D1D5DB]">{experience.description}</p>
            </article>
          ))}
        </div>
      </section>

      <h2 className="text-xs text-yellow-400">projects</h2>
      <section className="grid gap-x-6 gap-y-1 md:grid-cols-2">
        {projects.map((project) => (
          <ProjectCard
            key={project.title}
            title={project.title}
            description={project.description}
            imgUrl={project.imgUrl}
            seeCode={project.seeCode}
            liveSite={project.liveSite}
            tech={project.tech}
            status={project.status}
          />
        ))}
      </section>
    </div>
  )
}
export default page
