import { Metadata } from 'next'
import { greet, about } from '../utils/info'
import Link from 'next/link'

import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai'

import { ContactForm } from '@/components/contact-form'

export const metadata: Metadata = {
  title: 'Mitko | Developer, Designer, Creator',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="py-2">
      <h1 className="text-2xl font-bold text-[#D6D6DC]">{greet}</h1>
      <p className="my-4 max-w-lg text-base text-[#D6D6DC]">{about()}</p>
      <div className="mt-6 flex items-center justify-between">
        <div className="flex gap-2">
          <Link href="https://github.com/devemit" target="_blank">
            <AiFillGithub size={22} className="my-2 cursor-pointer text-[#A3A3A3] hover:text-[#333333]" />
          </Link>
          <Link href="https://www.linkedin.com/in/mitko-iliev/" target="_blank">
            <AiFillLinkedin size={22} className="my-2 cursor-pointer text-[#A3A3A3] hover:text-[#0A66C2]" />
          </Link>
        </div>
        <ContactForm />
      </div>
    </main>
  )
}
