import { Metadata } from 'next';
import { name, about, info } from '../utils/info';
import Link from 'next/link';

import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai';

import { ContactForm } from '@/components/contact-form';

export const metadata: Metadata = {
   title: 'Mitko',
   description: 'Generated by create next app',
};

export default function Home() {
   return (
      <main className='py-2'>
         <h1 className='text-[#D4D4D4] text-2xl font-bold'>{name}</h1>
         <p className='text-[#D4D4D4] my-6 text-base'>{info()}</p>
         <p className='text-[#D4D4D4] my-4 text-base max-w-lg'>{about()}</p>
         <div className='mt-6 justify-between flex'>
            <div className='flex gap-2'>
               <Link href='https://github.com/devemit' target='_blank'>
                  <AiFillGithub
                     size={22}
                     className='text-[#A3A3A3] my-2 cursor-pointer hover:text-[#D4D4D4]'
                  />
               </Link>
               <Link href='https://www.linkedin.com/in/mitko-iliev/' target='_blank'>
                  <AiFillLinkedin
                     size={22}
                     className='text-[#A3A3A3] my-2 cursor-pointer hover:text-[#D4D4D4]'
                  />
               </Link>
            </div>
            <p className='text-[#D4D4D4] my-4 text-[10px]'>© 2025 Mitko Devemit</p>
         </div>
         <div className='absolute bottom-0 right-0'>
            <ContactForm />
         </div>
      </main>
   );
}
