import { name, me, about, info } from '../utils/info';
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai';
import Image from 'next/image';
import Link from 'next/link';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Home | Mitko',
    description: 'Generated by create next app',
};

export default function Home() {
    return (
        <main className='py-2'>
            <h1 className='text-[#D4D4D4] text-2xl font-bold'>{name}</h1>
            <p className='text-[#D4D4D4] my-6 text-base'>{info()}</p>
            <div className='flex gap-5'>
                <Image
                    className='rounded-full my-2'
                    src={me}
                    alt='portrait'
                    width={110}
                    height={110}
                />
                <div className='mt-6'>
                    <Link href='https://github.com/devemit' target='_blank'>
                        <AiFillGithub
                            size={28}
                            className='text-[#A3A3A3] my-2 cursor-pointer hover:text-[#D4D4D4]'
                        />
                    </Link>
                    <Link href='https://www.linkedin.com/in/mitko-iliev/' target='_blank'>
                        <AiFillLinkedin
                            size={28}
                            className='text-[#A3A3A3] my-2 cursor-pointer hover:text-[#D4D4D4]'
                        />
                    </Link>
                </div>
            </div>
            <p className='text-[#D4D4D4] my-4 text-base max-w-lg'>{about()}</p>
        </main>
    );
}
