import { Metadata } from 'next'
import Button from '@/components/button'

export const metadata: Metadata = {
  title: 'What I do',
  description: 'Generated by create next app',
}
export default function About() {
  return (
    <section className="py-2">
      <h1 className="text-xl italic text-[#e87d7d]">what i do</h1>
      <br />
      <p className="text-sm text-[#D6D6DC]">
        I have nearly two years of professional experience specializing in React, TypeScript, and Redux, primarily at Technoperia, where I
        contribute to the development of Aduvi. My expertise includes designing reusable components, implementing efficient state
        management, and ensuring cross-device compatibility to deliver seamless user experiences.
      </p>
      <br />
      <p className="text-sm text-[#D6D6DC]">
        In addition to my core front-end skills, I possess substantial experience working with Blazor .NET, where I have developed
        interactive web components and managed complex state solutions for enterprise-scale healthcare and business applications. My
        comprehensive understanding of various development paradigms enables me to create robust, scalable solutions.
      </p>
      <br />
      <p className="text-sm text-[#D6D6DC]">
        I am proficient with modern CSS frameworks like Tailwind CSS, Ant-Design, server-side rendering with Next.js, and some basic
        knowledge of Node/Express.js, allowing me to deliver full-stack applications that prioritize performance, maintainability, and
        user-centric design.
      </p>
      <br />
      <div className="flex gap-2">
        <Button to={'https://github.com/devemit'}>Github</Button>
        <Button to={'https://www.linkedin.com/in/mitko-iliev/'}>Linkedin</Button>
      </div>
    </section>
  )
}
