import { Metadata } from 'next'
import Button from '@/components/button'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}
export default function About() {
  return (
    <section className="py-2">
      <h1 className="text-2xl text-[#D4D4D4]">My Skills</h1>
      <br />
      <p className="leading-relaxed text-[#D4D4D4]">
        In my toolbox, you&apos;ll find a versatile array of technologies, including JavaScript,
        TypeScript, HTML, CSS, React.js, Tailwind CSS, and Next.js. With these tools at my disposal,
        I craft responsive designs that adapt effortlessly to any device, while leveraging the
        latest trends and best practices to ensure optimal performance.
      </p>
      <br />
      <p className="leading-relaxed text-[#D4D4D4]">
        Additionally, I have experience working with server-side technologies such as Next.js, where
        I harness its power to create server-rendered React applications. This allows me to build
        robust and performant web applications that combine the flexibility of React with the
        scalability of server-side rendering.
      </p>
      <br />
      <p className="leading-relaxed text-[#D4D4D4]">
        While my expertise primarily lies in front-end development, I also dabble in the realms of
        C# and .NET, particularly harnessing the power of Blazor to build interactive web
        applications with precision and efficiency.
      </p>
      <br />
      <div className="flex gap-2">
        <Button to={'https://github.com/devemit'}>Github</Button>
        <Button to={'https://www.linkedin.com/in/mitko-iliev/'}>Linkedin</Button>
      </div>
    </section>
  )
}
