export const stack = [
   { src: '/Javascript.png', label: 'Javascript' },
   { src: '/Typescript.png', label: 'Typescript' },
   { src: '/netlogo.svg', label: '.NET' },
   { src: '/prisma.png', label: 'Prisma' },
   { src: '/bl.png', label: 'Blazor' },
   { src: '/React.png', label: 'React.js' },
   { src: '/svelte.png', label: 'Svelte' },
   { src: '/Astro.png', label: 'Astro.js' },
   { src: '/nxt.jpeg', label: 'Next.js' },
   { src: '/csharp.png', label: 'C#' },
   { src: '/Tailwind CSS.png', label: 'TailwindCSS' },
   { src: '/jest.jpg', label: 'Jest Testing' },
   { src: '/node.png', label: 'Node.js' },
   { src: '/MySQL.png', label: 'MySQL' },
   { src: '/Docker.png', label: 'Docker' },
];
