export const stack = [
  { src: '/claude.jpg', label: 'Claude Code AI' },
  { src: '/cursor.png', label: 'Cursor CLI' },
  { src: '/cursor.png', label: 'Cursor AI' },
  { src: '/Typescript.png', label: 'Typescript' },
  { src: '/React.png', label: 'React.js' },
  { src: '/Javascript.png', label: 'Javascript' },
  { src: '/netlogo.svg', label: '.NET' },
  { src: '/prisma.png', label: 'Prisma' },
  { src: '/bl.png', label: 'Blazor' },
  { src: '/Astro.png', label: 'Astro.js' },
  { src: '/nxt.jpeg', label: 'Next.js' },
  { src: '/csharp.png', label: 'C#' },
  { src: '/Tailwind CSS.png', label: 'Tailwind' },
  { src: '/node.png', label: 'Node.js' },
  { src: '/posq.png', label: 'PostgreSQL' },
  { src: '/Docker.png', label: 'Docker' },
  { src: '/git.png', label: 'Git' },
  { src: '/css.png', label: 'css' },
  { src: '/sass.png', label: 'sass' },
]
