import Image from 'next/image'
import { Metadata } from 'next'

import { stack } from '@/utils/stack'

export const metadata: Metadata = {
  title: 'Techstack',
  description: 'Generated by create next app',
}

export default function TechStack() {
  const shuffledStack = [...stack].sort(() => Math.random() - 0.5)

  return (
    <section className="flex flex-col gap-4 py-2">
      <h1 className="text-2xl text-[#D6D6DC]">Tech Stack</h1>
      <p className="text-md max-w-sm text-[#D6D6DC] md:max-w-md">
        Here is my favourite Tech Stack, languages and frameworks that i use every day in most of my projects.
      </p>
      <div className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-2">
        {shuffledStack.map((ele, index) => (
          <div className="flex items-center gap-5" key={index}>
            {ele.src ? (
              <Image src={ele.src} width={30} height={30} alt="tech" className="rounded-sm" />
            ) : (
              <div className="h-8 w-8 rounded-sm bg-[#111016]" />
            )}
            <span className="rounded-sm bg-slate-900 p-1 text-sm tracking-wider text-[#D6D6DC]">{ele.label}</span>
          </div>
        ))}
      </div>
    </section>
  )
}
