import Image from 'next/image';
import { Metadata } from 'next';

import { stack } from '@/utils/stack';

export const metadata: Metadata = {
   title: 'Techstack',
   description: 'Generated by create next app',
};

export default function TechStack() {
   return (
      <section className='flex flex-col gap-4 py-2'>
         <h1 className='text-2xl text-[#D4D4D4]'>Tech Stack</h1>
         <p className='max-w-sm md:max-w-md text-md text-[#D4D4D4] leading-relaxed'>
            Here is my favourite Tech Stack, languages and frameworks that i use every day in most
            of my projects.
         </p>
         <div className='grid grid-cols-1 md:grid-cols-2 gap-4 mt-10'>
            {stack.map((ele, index) => (
               <div className='flex items-center gap-5' key={index}>
                  <Image src={ele.src} width={38} height={38} alt='tech' className='rounded-sm' />
                  <span className=' text-[#D4D4D4] text-sm uppercase tracking-wider '>
                     {ele.label}
                  </span>
               </div>
            ))}
         </div>
      </section>
   );
}
